/////// OPTION 1 ///////
// Use import/export syntax to get data generated by a
// javascript file (data.js here).
////////////////////////

import {pets, monsters} from './pets.js';

/////// OPTION 2 ///////
// Use import/export syntax to get data hard-coded
// as static data into a JSON file (weapons.json here).
////////////////////////

// import data from './pets.json' with {type: 'json'};
// const pets = data;

/////// OPTION 3 ///////
// Use fetch syntax to fetch the data across the network
// from the server that is serving it (here, our own 
// Live Server instance).
////////////////////////

// const get_pet_data_from_elsewhere = () => {
//     const pets_data = fetch('pets.json')
//         .then(response => {
//             return response.json();
//         })
//         .then(result => {
//             return result;
//         });
        
//     return pets_data;
// }

// const pets = await get_pet_data_from_elsewhere();

/////// THE CODE ///////
// After getting our data from elsewhere (however we do it),
// do something with it.
////////////////////////
import { all_pets_to_html} from './pets_to_html.js';

const pet_html = all_pets_to_html(pets);

const set_html = (html_string) => {
    document.querySelector('#the_list').outerHTML = html_string;
}

set_html(pet_html);